WIP: Optional nb
asmeurer/removestar pull request #54
Opened 2023-11-01 18:18 UTC by Saransh-cpp

Make nb dependencies optional

2023-11-01 18:19 UTC, Saransh-cpp commented on .github/workflows/ci.yml
> +      - name: Test removestar (lite)
```suggestion
      - name: Test removestar (nb)
```

2024-03-13 02:51 UTC, wimglenn commented
Is there a reason this is still Draft?

2024-03-13 13:49 UTC, Saransh-cpp commented
Forgot about this. IIRC this worked and I could not extract the nb logic to a separate file. I'll merge the PR this week and create a new release.

2024-03-14 20:58 UTC, kieran-ryan requested changes
Thanks for circling back on this @Saransh-cpp - much appreciated!

Just the one changed requested if you could take a look.

Separately I noticed there's a warning when IPython is not installed. Typically, this will not be observed as it installs with Jupyter, however, it will be prevalent in CI contexts where Jupyter is unlocked to be installed. It would be great if you could check whether there are different APIs or ways we could suppress this warning if we are not calling any code that could potentially trigger an error due to a missing python dependency.

```
removestar/venv/share/jupyter/nbconvert/templates/python/index.py.j2:61: UserWarning: IPython is needed to transform IPython syntax to pure Python. Install ipython if you need this functionality.
```

2024-03-14 20:58 UTC, kieran-ryan commented on removestar/__main__.py
> +import importlib
Believe this needs to be `import importlib.util` on [later versions of Python](https://discuss.python.org/t/python3-11-importlib-no-longer-exposes-util/25641).

```console
    and importlib.util.find_spec("nbconvert") is not None
AttributeError: module 'importlib' has no attribute 'util'
```

2024-03-15 10:53 UTC, Saransh-cpp commented
Thanks for the review, @kieran-ryan!

I could not reproduce the warning locally. I tried uninstalling `ipython` once `jupyter` was installed, but the warning did not appear on running removestar. Could you please attach a MWE or take a look at this? Thanks!

2024-03-24 17:32 UTC, kieran-ryan commented
@Saransh-cpp, using Python `3.11.2`, if I uninstall jupyter and ipython - and verify they are uninstalled through `pip freeze` or by attempting to run them from the command line; if I pip install `removestar 1.6.dev11+ge60ca6a` and run it against a jupyter notebook (as below), I observe the error. Would you able to advise whether applying similar reproduces the issue?

```python
from behave import *

print(step)
```

```console
➜  removestar behave.ipynb                                                          
/Users/<user>/projects/removestar/venv/share/jupyter/nbconvert/templates/python/index.py.j2:61: UserWarning: IPython is needed to transform IPython syntax to pure Python. Install ipython if you need this functionality.
--- original/behave.ipynb
+++ fixed/behave.ipynb
@@ -4,6 +4,6 @@
 # In[ ]:
 
 
-from behave import *
+from behave import step
 
 print(step)
```

2024-03-24 17:33 UTC, kieran-ryan approved these changes

2024-04-08 16:36 UTC, Saransh-cpp commented
HI, @kieran-ryan, sorry for the late reply. I am not getting any time to look into the warning, but the warning looks okay to me, given that it is advising the users towards the correct usage of removestar. Could you please try resolving it if you feel otherwise? I think the warning is quite informative, and we should not suppress it.

2024-04-08 16:54 UTC, kieran-ryan commented
No worries, thanks for reply @Saransh-cpp, I will have another look when I can.

The error relates to whether a dependency is internally installed with `removestar`, rather than relating to the user's software the package is run against; so my present thinking would be best to either suppress the warning if it does not affect functionality and if the dependency is not required; or otherwise mark it as a required dependency of `removestar` so it is installed with the package and not raised. Though will take a look and see if there's a satisfactory mitigation.

2024-04-08 16:56 UTC, Saransh-cpp commented
Sounds good, thanks for taking a look! :)

2024-06-04 14:00 UTC, Saransh-cpp commented
Hi, @kieran-ryan! A gentle ping. Did you make any progress on this?

2024-08-14 10:09 UTC, Saransh-cpp commented
Hi @kieran-ryan, I tried this locally again (with fresh eyes and environment) and wasn't able to reproduce -

```py
(.env) saransh@Saranshs-MacBook-Air Projects % python3 -m pip freeze       
numpy==2.0.1
pyflakes==3.2.0
-e git+https://github.com/asmeurer/removestar.git@10365a249bb7893a48578f0d7c8b3c0b0da69ac1#egg=removestar
(.env) saransh@Saranshs-MacBook-Air Projects % removestar test.ipynb 
--- original/test.ipynb
+++ fixed/test.ipynb
@@ -4,7 +4,7 @@
 # In[ ]:
 
 
-from numpy import *
+from numpy import array
 
 a = array([1, 2, 3])
```

I will go ahead and merge this. We can fix the warning if someone reports it or if you encounter it again/

2024-08-14 10:11 UTC, merged